Update Eclipse Paho to version 1.4.1
eclipse-kanto/local-digital-twins pull request #8
Opened 2022-08-22 16:26 UTC by antonia-avramova

[#7] Update Eclipse Paho to version 1.4.1

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2022-08-22 20:43 UTC, e-grigorov commented
@antonia-avramova The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

2022-08-22 20:52 UTC, e-grigorov requested changes

2022-08-22 20:52 UTC, e-grigorov commented on go.sum
>  github.com/eclipse/paho.mqtt.golang v1.3.5 h1:sWtmgNxYM9P2sP+xEItMozsR3w0cqZFlqnNN1bdl41Y=
Could you please run: `go mod tidy`, it'll remove this line?

2022-08-22 20:52 UTC, e-grigorov commented on NOTICE.md
> +golang.org/x/sync (v0.0.0-20210220032951-036812b2e83c)
To keep the readability, I would suggest to put it between net and sys.

2022-08-23 06:19 UTC, antonia-avramova commented
> @antonia-avramova The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances 😊
> 
> Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

I understand and agree with the license change explained above.

2022-08-23 07:57 UTC, e-grigorov approved these changes

2022-08-23 07:58 UTC, merged